services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: blacklotus
      POSTGRES_USER: blacklotus_user
      POSTGRES_PASSWORD: blacklotus_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blacklotus_user -d blacklotus"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://blacklotus_user:blacklotus_password@postgres:5432/blacklotus
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=GxXMDwy7dhlG7F+K2Fj5v873RSAkHpRbpSir18lz344=
      - RESEND_API_KEY=re_WXUc2XAs_2qicMXr2gHiqM8kQ7kmzGYWq
      - EMAIL_FROM=Dark Lotus <noreply@darklotus.party>
      - APP_BASE_URL=http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build: .
    command: node worker/index.js
    environment:
      - DATABASE_URL=postgresql://blacklotus_user:blacklotus_password@postgres:5432/blacklotus
      - REDIS_URL=redis://redis:6379
      - RESEND_API_KEY=re_WXUc2XAs_2qicMXr2gHiqM8kQ7kmzGYWq
      - EMAIL_FROM=Dark Lotus <noreply@darklotus.party>
      - APP_BASE_URL=http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_data:
  redis_data:
